# Generated by Django 6.0.6 on 2026-06-24 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Berçário, Maternal I', max_length=100)),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_professor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='core.turma')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('acolhida', models.CharField(max_length=50)),
                ('estimulacao', models.JSONField(default=list)),
                ('lanche_manha', models.CharField(max_length=50)),
                ('almoco', models.CharField(max_length=50)),
                ('lanche_tarde', models.CharField(max_length=50)),
                ('soneca', models.CharField(max_length=50)),
                ('febre', models.CharField(max_length=50)),
                ('temperatura', models.CharField(blank=True, max_length=20, null=True)),
                ('hidratacao', models.CharField(blank=True, max_length=50, null=True)),
                ('higiene', models.JSONField(default=list)),
                ('pedagoga', models.CharField(max_length=100)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotinas', to='core.aluno')),
            ],
            options={
                'unique_together': {('aluno', 'data')},
            },
        ),
    ]
